[build]
  command = "CI=false npm run build"
  publish = "build"

# Règle de redirection pour React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Variables d'environnement pour le build
[build.environment]
  CI = "false"

# Configuration des en-têtes pour gérer CORS
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
